# Basic Pandas for Data Science

## Package Import

In [3]:
import pandas as pd
import numpy as np

## Dataset Import

The dataset used in this notebook is from [Kaggle - Pokemon](https://www.kaggle.com/datasets/abcsds/pokemon).

## Manually Create a DataFrame

From a Dictionary\
The columns order is the order of keys insertion:

In [ ]:
df = pd.DataFrame({'Column 1': [100,200], 'Column 2': [300,400]})
df

   Column 1  Column 2
0       100       300
1       200       400

From a list of random values w/ column names:

In [5]:
pd.DataFrame(np.random.rand(4, 8), columns=list('abcdefgh'))

,a,b,c,d,e,f,g,h
0,0.896989,0.828643,0.840180,0.915293,0.015455,0.537308,0.159890,0.036243
1,0.853145,0.820541,0.484513,0.578945,0.210457,0.256412,0.211360,0.114042
2,0.344668,0.404570,0.672889,0.540809,0.494076,0.234354,0.630560,0.838077
3,0.869002,0.615523,0.237715,0.483252,0.958088,0.565652,0.674273,0.214110

From a dictionary including Series:

In [15]:
pd.DataFrame({'col1': [0,1,2,3], 'col2': pd.Series([2,3], index=[2,3])}, index=[0,1,2,3])

   col1  col2
0     0   NaN
1     1   NaN
2     2   2.0
3     3   3.0

From numpy ndarray:

In [16]:
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
                   columns=['a', 'b', 'c'])
df

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

From a numpy ndarray that has labeled columns:

In [17]:
data = np.array([(1,2,3), (4,5,6), (7,8,9)], dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")])
df = pd.DataFrame(data=data, columns=['c', 'a'])
df

   c  a
0  3  1
1  6  4
2  9  7

From Series/DataFrame:

In [19]:
ser = pd.Series([1,2,3], index=['a','b','c'])
df = pd.DataFrame(data=ser, index=['c', 'a'], columns=['hehe'])
df

   hehe
c     3
a     1

If we construct from DataFrame, then the columns in the new DataFrame must be a subset of the original columns. If not, the new columns will be filled with NaN.

In [ ]:
df1 = pd.DataFrame([1,2,3], index=['a','b','c'], columns=['x'])
df2 = pd.DataFrame(data=df1, index=['c', 'a'])
df3 = pd.DataFrame(data=df1, index=['c', 'a'], columns=['z'])
print(df2, '\n',df3)

   0
c  3
a  1
     z
c NaN
a NaN

## Reverse Row/Column Order

See also `iloc` [here](https://cornel05.github.io/cornel.ai/notebooks/snippets/pandas/basic_pandas/basic_pandas_1.html#iloc-and-loc-in-pandas)

In [26]:
data.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

### Row

In [34]:
data.iloc[::-1].head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True

See also `reset_index` [here](https://cornel05.github.io/cornel.ai/notebooks/snippets/pandas/basic_pandas/basic_pandas_1.html#reset-index).

In [35]:
data.iloc[::-1].reset_index().head()

,index,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True
1,798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
2,797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
3,796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
4,795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True

In [36]:
data.iloc[::-1].reset_index(drop=True).head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True
1,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
2,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
3,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
4,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True

### Column

In [33]:
data.iloc[:, ::-1].head()

,Legendary,Generation,Speed,Sp. Def,Sp. Atk,Defense,Attack,HP,Total,Type 2,Type 1,Name,#
0,False,1,45,65,65,49,49,45,318,Poison,Grass,Bulbasaur,1
1,False,1,60,80,80,63,62,60,405,Poison,Grass,Ivysaur,2
2,False,1,80,100,100,83,82,80,525,Poison,Grass,Venusaur,3
3,False,1,80,120,122,123,100,80,625,Poison,Grass,VenusaurMega Venusaur,3
4,False,1,65,50,60,43,52,39,309,NaN,Fire,Charmander,4