# pandas: Split String into Multiple Columns

## Package Import

In [1]:
import pandas as pd
import numpy as np

## Dataset Import

The dataset used in this notebook is from [Kaggle - Pokemon](https://www.kaggle.com/datasets/abcsds/pokemon).

In [2]:
data = pd.read_csv('data/Pokemon.csv')

## Split a string into multiple columns:

This is extremely useful when we have `Name`, and we want to split into `First`,`Middle`,`Last`:

In [3]:
df = pd.DataFrame(dict(name=['John Arthur Doe', 'Jane Ann Smith'], location=['Los Angeles, CA', 'Washington, DC']))
df

              name         location
0  John Arthur Doe  Los Angeles, CA
1   Jane Ann Smith   Washington, DC

In [4]:
df[['first','middle','last']] = df.name.str.split(expand=True) # if not specify delimiters, split based on whitespace
df

              name         location first  middle   last
0  John Arthur Doe  Los Angeles, CA  John  Arthur    Doe
1   Jane Ann Smith   Washington, DC  Jane     Ann  Smith