# pandas:  Filtering data

In [1]:
import pandas as pd

## Loading data into Pandas DataFrame
The dataset is from [Kaggle - Pokemon](https://www.kaggle.com/datasets/abcsds/pokemon).

In [2]:
data = pd.read_csv('data/Pokemon.csv')

We can filter with multiple conditions at ease.

In [3]:
data.loc[(data['Type 1'] == 'Grass') & (data['Type 2'] == 'Poison')].head(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False

In [4]:
data.loc[(data['Type 1'] == 'Grass') | (data['Type 2'] == 'Poison')][0::10].loc[data['HP'] > 50].head(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
50,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
101,94,Gengar,Ghost,Poison,500,60,65,60,130,75,110,1,False
197,182,Bellossom,Grass,NaN,490,75,80,95,90,100,50,2,False