# pandas: Create DataFrame

## Package Import

In [1]:
import pandas as pd
import numpy as np

## Dataset Import

The dataset used in this notebook is from [Kaggle - Pokemon](https://www.kaggle.com/datasets/abcsds/pokemon).

In [2]:
data = pd.read_csv('data/Pokemon.csv')

## Manually Create a DataFrame

From a Dictionary\
The columns order is the order of keys insertion:

In [3]:
df = pd.DataFrame({'Column 1': [100,200], 'Column 2': [300,400]})
df

   Column 1  Column 2
0       100       300
1       200       400

From a list of random values w/ column names:

In [4]:
pd.DataFrame(np.random.rand(4, 8), columns=list('abcdefgh'))

,a,b,c,d,e,f,g,h
0,0.530107,0.094573,0.202908,0.491082,0.659014,0.729337,0.299216,0.177274
1,0.710210,0.215153,0.155433,0.234487,0.432326,0.163094,0.240919,0.504118
2,0.499845,0.540403,0.440626,0.251292,0.529687,0.921588,0.333904,0.518168
3,0.873400,0.509635,0.491841,0.333138,0.060832,0.910975,0.002949,0.374984

From a dictionary including Series:

In [5]:
pd.DataFrame({'col1': [0,1,2,3], 'col2': pd.Series([2,3], index=[2,3])}, index=[0,1,2,3])

   col1  col2
0     0   NaN
1     1   NaN
2     2   2.0
3     3   3.0

From numpy ndarray:

In [6]:
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
                   columns=['a', 'b', 'c'])
df

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

From a numpy ndarray that has labeled columns:

In [7]:
d = np.array([(1,2,3), (4,5,6), (7,8,9)], dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")])
df = pd.DataFrame(data=d, columns=['c', 'a'])
df

   c  a
0  3  1
1  6  4
2  9  7

From Series/DataFrame:

In [8]:
ser = pd.Series([1,2,3], index=['a','b','c'])
df = pd.DataFrame(data=ser, index=['c', 'a'], columns=['hehe'])
df

   hehe
c     3
a     1

If we construct from DataFrame, then the columns in the new DataFrame must be a subset of the original columns. If not, the new columns will be filled with NaN.

In [9]:
df1 = pd.DataFrame([1,2,3], index=['a','b','c'], columns=['x'])
df2 = pd.DataFrame(data=df1, index=['c', 'a'])
df3 = pd.DataFrame(data=df1, index=['c', 'a'], columns=['z'])
print(df2, '\n',df3)

   x
c  3
a  1
     z
c NaN
a NaN