# pandas:  Sorting

In [1]:
import pandas as pd

## Loading data into Pandas DataFrame
The dataset is from [Kaggle - Pokemon](https://www.kaggle.com/datasets/abcsds/pokemon).

In [2]:
data = pd.read_csv('data/Pokemon.csv')

## Sort by 1 column, ascending

In [3]:
data.sort_values('Type 1').head(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
600,540,Sewaddle,Bug,Grass,310,45,53,70,40,60,42,5,False
136,127,Pinsir,Bug,NaN,500,65,125,100,55,70,85,1,False
457,412,Burmy,Bug,NaN,224,40,29,45,29,45,36,4,False

## Sort by 1 column, descending

In [4]:
data.sort_values('Type 1', ascending=False).head(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
371,339,Barboach,Water,Ground,288,50,48,43,46,41,60,3,False
97,90,Shellder,Water,NaN,305,30,65,100,45,25,40,1,False
240,222,Corsola,Water,Rock,380,55,55,85,65,85,35,2,False

## Sort by multiple columns, 1 = ascending, 0 = descending

In [5]:
data.sort_values(['Type 1', 'HP'], ascending=[1, 0]).head(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,515,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,550,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,500,80,125,75,40,95,85,2,False