# pandas: Basic Pandas for Data Science

## Package Import

In [1]:
import pandas as pd
import numpy as np

## Dataset Import

The dataset used in this notebook is from [Kaggle - Pokemon](https://www.kaggle.com/datasets/abcsds/pokemon).

In [2]:
data = pd.read_csv('data/Pokemon.csv')

## Manually Create a DataFrame

From a Dictionary\
The columns order is the order of keys insertion:

In [3]:
df = pd.DataFrame({'Column 1': [100,200], 'Column 2': [300,400]})
df

   Column 1  Column 2
0       100       300
1       200       400

From a list of random values w/ column names:

In [4]:
pd.DataFrame(np.random.rand(4, 8), columns=list('abcdefgh'))

,a,b,c,d,e,f,g,h
0,0.205424,0.670769,0.620837,0.494566,0.519732,0.278287,0.430929,0.144582
1,0.325890,0.168820,0.010125,0.697101,0.865195,0.026785,0.841430,0.378895
2,0.859424,0.550560,0.158674,0.942003,0.353605,0.485818,0.622277,0.587977
3,0.421407,0.687107,0.818512,0.107829,0.918829,0.669242,0.535026,0.621689

From a dictionary including Series:

In [5]:
pd.DataFrame({'col1': [0,1,2,3], 'col2': pd.Series([2,3], index=[2,3])}, index=[0,1,2,3])

   col1  col2
0     0   NaN
1     1   NaN
2     2   2.0
3     3   3.0

From numpy ndarray:

In [6]:
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
                   columns=['a', 'b', 'c'])
df

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

From a numpy ndarray that has labeled columns:

In [7]:
d = np.array([(1,2,3), (4,5,6), (7,8,9)], dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")])
df = pd.DataFrame(data=d, columns=['c', 'a'])
df

   c  a
0  3  1
1  6  4
2  9  7

From Series/DataFrame:

In [8]:
ser = pd.Series([1,2,3], index=['a','b','c'])
df = pd.DataFrame(data=ser, index=['c', 'a'], columns=['hehe'])
df

   hehe
c     3
a     1

If we construct from DataFrame, then the columns in the new DataFrame must be a subset of the original columns. If not, the new columns will be filled with NaN.

In [9]:
df1 = pd.DataFrame([1,2,3], index=['a','b','c'], columns=['x'])
df2 = pd.DataFrame(data=df1, index=['c', 'a'])
df3 = pd.DataFrame(data=df1, index=['c', 'a'], columns=['z'])
print(df2, '\n',df3)

   x
c  3
a  1
     z
c NaN
a NaN

## Reverse Row/Column Order

See also `iloc` [here](https://cornel05.github.io/cornel.ai/notebooks/snippets/pandas/basic_pandas/basic_pandas_1.html#iloc-and-loc-in-pandas)

In [10]:
data.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

### Row

In [11]:
data.iloc[::-1].head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True

See also `reset_index` [here](https://cornel05.github.io/cornel.ai/notebooks/snippets/pandas/basic_pandas/basic_pandas_1.html#reset-index).

In [12]:
data.iloc[::-1].reset_index().head()

,index,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True
1,798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
2,797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
3,796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
4,795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True

In [13]:
data.iloc[::-1].reset_index(drop=True).head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True
1,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
2,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
3,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
4,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True

### Column

In [14]:
data.iloc[:, ::-1].head()

,Legendary,Generation,Speed,Sp. Def,Sp. Atk,Defense,Attack,HP,Total,Type 2,Type 1,Name,#
0,False,1,45,65,65,49,49,45,318,Poison,Grass,Bulbasaur,1
1,False,1,60,80,80,63,62,60,405,Poison,Grass,Ivysaur,2
2,False,1,80,100,100,83,82,80,525,Poison,Grass,Venusaur,3
3,False,1,80,120,122,123,100,80,625,Poison,Grass,VenusaurMega Venusaur,3
4,False,1,65,50,60,43,52,39,309,NaN,Fire,Charmander,4

## Select column by data type

Check columns data types:

In [15]:
data.dtypes

#              int64
Name          object
Type 1        object
Type 2        object
Total          int64
HP             int64
Attack         int64
Defense        int64
Sp. Atk        int64
Sp. Def        int64
Speed          int64
Generation     int64
Legendary       bool
dtype: object

Select all columns that are int or float:

In [16]:
data.select_dtypes(include='number').head()

   #  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation
0  1    318  45      49       49       65       65     45           1
1  2    405  60      62       63       80       80     60           1
2  3    525  80      82       83      100      100     80           1
3  3    625  80     100      123      122      120     80           1
4  4    309  39      52       43       60       50     65           1

Select multiple types by passing as a list:

In [17]:
data.select_dtypes(include=['number', 'object']).head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1

Or exclude types by using `exclude` parameter:

In [18]:
data.select_dtypes(exclude=['number', 'object']).head()

   Legendary
0      False
1      False
2      False
3      False
4      False

## Convert strings to numbers

In [19]:
df = pd.DataFrame({'col1': ['1.1', '2.2', '3.3'], 'col2': ['4.4', '5.5', '6.6'], 'col3': ['7.7', '8.8', '-']})
df, df.dtypes

(  col1 col2 col3
 0  1.1  4.4  7.7
 1  2.2  5.5  8.8
 2  3.3  6.6    -,
 col1    object
 col2    object
 col3    object
 dtype: object)

`df.astype()` can convert multiple columns at once. Use `errors='ignore'` to skip conversion errors.

In [20]:
df.astype({'col1': 'float', 'col2': 'float'}, errors='raise').dtypes

col1    float64
col2    float64
col3     object
dtype: object

In [21]:
df.astype({'col1': 'float', 'col2': 'float', 'col3': 'float'}, errors='ignore').dtypes

col1    float64
col2    float64
col3     object
dtype: object

A better way to convert strings to numbers is to use `pd.to_numeric()` with `errors='coerce'` to convert invalid parsing to NaN.

In [22]:
pd.to_numeric(df.col3, errors='coerce')

0    7.7
1    8.8
2    NaN
Name: col3, dtype: float64

In [23]:
pd.to_numeric(df.col3, errors='coerce').fillna(0)

0    7.7
1    8.8
2    0.0
Name: col3, dtype: float64

In [24]:
df = df.apply(pd.to_numeric, errors='coerce').fillna(0)
df, df.dtypes

(   col1  col2  col3
 0   1.1   4.4   7.7
 1   2.2   5.5   8.8
 2   3.3   6.6   0.0,
 col1    float64
 col2    float64
 col3    float64
 dtype: object)

## Deal with large datasets

### Check memory usage

In [25]:
data.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 179.0 KB